import { useRef } from "react";
import { formatCurrency, formatDate } from "../../utils/helpers";
import { X, Download, Printer, CheckCircle2, TrendingUp, TrendingDown } from "lucide-react";
import "./ReceiptModal.css";

const ReceiptModal = ({ transaction: t, onClose }) => {
  const receiptRef = useRef(null);

  const isIncome = t.type === "income";

  const handlePrint = () => window.print();

  const handleDownload = () => {
    // Build a self-contained HTML string and trigger download
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Receipt – ${t.description}</title>
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family: 'Segoe UI', sans-serif; background:#f5f6fa; display:flex; align-items:center; justify-content:center; min-height:100vh; padding:24px; }
    .receipt { background:#fff; border-radius:16px; width:100%; max-width:400px; padding:32px 28px; box-shadow:0 8px 32px rgba(0,0,0,.12); }
    .top { text-align:center; margin-bottom:24px; }
    .logo { font-size:22px; font-weight:800; color:#7C6EF8; letter-spacing:-1px; }
    .logo span { color:#16151E; }
    .subtitle { font-size:11px; color:#9896AF; text-transform:uppercase; letter-spacing:.08em; margin-top:2px; }
    .status { display:inline-flex; align-items:center; gap:6px; margin-top:14px; padding:6px 16px; border-radius:50px; font-size:12px; font-weight:700; }
    .status.income  { background:#e6fff5; color:#16a34a; }
    .status.expense { background:#fff0f3; color:#dc2626; }
    .amount-box { text-align:center; padding:18px; background:#f7f8fc; border-radius:12px; margin:0 0 20px; }
    .amount-label { font-size:11px; color:#9896AF; text-transform:uppercase; letter-spacing:.07em; }
    .amount { font-size:34px; font-weight:800; letter-spacing:-2px; margin-top:4px; }
    .amount.income  { color:#16a34a; }
    .amount.expense { color:#dc2626; }
    .rows { border-top:1px solid #e4e4ef; }
    .row { display:flex; justify-content:space-between; padding:11px 0; border-bottom:1px dashed #e4e4ef; font-size:13px; }
    .row:last-child { border-bottom:none; }
    .row-label { color:#9896AF; }
    .row-value { font-weight:600; color:#16151E; }
    .badge { display:inline-block; padding:2px 10px; border-radius:50px; font-size:11px; font-weight:700; }
    .badge.income  { background:#e6fff5; color:#16a34a; }
    .badge.expense { background:#fff0f3; color:#dc2626; }
    .footer { text-align:center; margin-top:20px; padding-top:16px; border-top:1px dashed #e4e4ef; }
    .footer p { font-size:11px; color:#9896AF; }
    .receipt-id { font-size:10px; color:#c4c2d4; margin-top:6px; font-family:monospace; }
  </style>
</head>
<body>
  <div class="receipt">
    <div class="top">
      <div class="logo">Fin<span>Dash</span></div>
      <div class="subtitle">Finance Intelligence</div>
      <div class="status ${t.type}">${isIncome ? "✓ Income Received" : "✓ Expense Recorded"}</div>
    </div>
    <div class="amount-box">
      <div class="amount-label">Amount</div>
      <div class="amount ${t.type}">${isIncome ? "+" : "-"}${formatCurrency(t.amount)}</div>
    </div>
    <div class="rows">
      <div class="row"><span class="row-label">Description</span><span class="row-value">${t.description}</span></div>
      <div class="row"><span class="row-label">Category</span><span class="row-value">${t.category}</span></div>
      <div class="row"><span class="row-label">Date</span><span class="row-value">${formatDate(t.date)}</span></div>
      <div class="row"><span class="row-label">Type</span><span class="badge ${t.type}">${t.type}</span></div>
      <div class="row"><span class="row-label">Transaction ID</span><span class="row-value" style="font-family:monospace;font-size:11px">#${String(t.id).slice(0,12)}</span></div>
    </div>
    <div class="footer">
      <p>Generated by FinDash · ${new Date().toLocaleDateString("en-IN", { day:"numeric", month:"short", year:"numeric" })}</p>
      <div class="receipt-id">REF-${String(t.id).toUpperCase().slice(-8)}</div>
    </div>
  </div>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = `receipt-${t.description.replace(/\s+/g, "-").toLowerCase()}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="receipt-overlay" onClick={onClose}>
      <div className="receipt-modal" onClick={(e) => e.stopPropagation()}>

        {/* Header */}
        <div className="receipt-modal-header">
          <span className="receipt-modal-title">Transaction Receipt</span>
          <button className="receipt-close" onClick={onClose}><X size={17} /></button>
        </div>

        {/* Receipt card */}
        <div className="receipt-card" ref={receiptRef} id="receipt-printable">

          {/* Brand */}
          <div className="receipt-brand">
            <p className="receipt-brand-name">Fin<span>Dash</span></p>
            <p className="receipt-brand-sub">Finance Intelligence</p>
          </div>

          {/* Status pill */}
          <div className={`receipt-status ${t.type}`}>
            <CheckCircle2 size={14} />
            {isIncome ? "Income Received" : "Expense Recorded"}
          </div>

          {/* Amount */}
          <div className="receipt-amount-box">
            <p className="receipt-amount-label">Amount</p>
            <p className={`receipt-amount ${t.type}`}>
              {isIncome ? "+" : "−"}{formatCurrency(t.amount)}
            </p>
          </div>

          {/* Rows */}
          <div className="receipt-rows">
            {[
              { label: "Description", value: t.description },
              { label: "Category",    value: t.category },
              { label: "Date",        value: formatDate(t.date) },
              { label: "Type",        value: (
                <span className={`receipt-type-badge ${t.type}`}>
                  {isIncome ? <TrendingUp size={11} /> : <TrendingDown size={11} />}
                  {t.type}
                </span>
              )},
              { label: "Reference",   value: <code className="receipt-ref">#{String(t.id).toUpperCase().slice(-10)}</code> },
            ].map(({ label, value }) => (
              <div className="receipt-row" key={label}>
                <span className="receipt-row-label">{label}</span>
                <span className="receipt-row-value">{value}</span>
              </div>
            ))}
          </div>

          {/* Divider */}
          <div className="receipt-dashed-divider" />

          {/* Footer */}
          <div className="receipt-footer">
            <p>Generated by FinDash</p>
            <p className="receipt-date">
              {new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}
            </p>
          </div>
        </div>

        {/* Actions */}
        <div className="receipt-actions">
          <button className="receipt-btn secondary" onClick={handlePrint}>
            <Printer size={15} /> Print
          </button>
          <button className="receipt-btn primary" onClick={handleDownload}>
            <Download size={15} /> Download HTML
          </button>
        </div>
      </div>
    </div>
  );
};

export default ReceiptModal;